name: Lint

on:
  workflow_dispatch:
  push:
    paths:
      - "**.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.10'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install --upgrade flake8 isort blue mypy types-PyYAML bandit safety

    - name: Run lint
      run: isort .

    - name: Run blue formatter
      run: make format

    - name: Run flake8
      run: |
        flake8 . --count --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=4

    - name: Run mypy / static types
      run: make static-check

    - name: Run bandit
      run: bandit pygithubactions

    - name: Run safety
      run: safety check
