name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    paths-ignore: [ 'docs/**', '*.md', '*.yaml', '*.yml', '*.toml' ]
    branches:
      - 'main'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.10'
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest pytest-cov
          make install-local

      - name: Run tests
        run: make test
